services:
  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    environment:
      - PUBLIC_SERVER_URL=http://server:8000
      - ORIGIN=http://localhost:8080
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - "8080:3000"
    depends_on:
      - server

  db:
    image: postgis/postgis:15-3.3
    container_name: adventurelog-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: changeme123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adventure -d database"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=changeme123
      - SECRET_KEY=changeme123
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='http://localhost:81'
      - CSRF_TRUSTED_ORIGINS=https://api.adventurelog.app,https://adventurelog.app,http://localhost:8080,http://localhost:81
      - DEBUG=False
      - FRONTEND_URL='http://localhost:8080'
    ports:
      - "8055:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - adventurelog_media:/code/media/

  nginx:
    image: nginx:latest
    container_name: adventurelog-nginx
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - adventurelog_media:/app/media
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

volumes:
  postgres_data:
    name: adventurelog_postgres_data
  adventurelog_media:
    name: adventurelog_media_data